import { Post, Competitor, NewsItem, MonthlyMetric, EngagementMetric } from './types';

export const samplePosts: Post[] = [
  {
    id: '1',
    title: 'Morning Routine That Changed My Life',
    caption: 'Start your day the right way. Here\'s the exact morning routine I\'ve been following for 6 months that transformed my productivity and mindset completely.',
    platform: 'Instagram',
    status: 'Scheduled',
    type: 'Reel',
    scheduledDate: '2026-03-25',
    createdAt: '2026-03-18T10:00:00Z',
  },
  {
    id: '2',
    title: '5 LinkedIn Growth Hacks',
    caption: 'These 5 LinkedIn strategies grew my profile from 2K to 64K followers in just 8 months. No ads, no shortcuts — just smart content and consistency.',
    platform: 'LinkedIn',
    status: 'Published',
    type: 'Video',
    scheduledDate: '2026-03-10',
    createdAt: '2026-03-08T14:00:00Z',
  },
  {
    id: '3',
    title: 'Brand Identity Deep Dive',
    caption: 'A comprehensive look at what makes a brand truly memorable. We\'re breaking down the psychology behind top brand identities and what you can learn from them.',
    platform: 'YouTube',
    status: 'In Progress',
    type: 'Video',
    scheduledDate: null,
    createdAt: '2026-03-15T09:00:00Z',
  },
  {
    id: '4',
    title: 'Behind the Scenes: Agency Life',
    caption: 'Ever wonder what it\'s actually like running a digital marketing agency? We\'re pulling back the curtain on our day-to-day operations, wins, and challenges.',
    platform: 'Instagram',
    status: 'Ready',
    type: 'Story',
    scheduledDate: '2026-03-28',
    createdAt: '2026-03-20T11:00:00Z',
  },
  {
    id: '5',
    title: 'Content Strategy for 2026',
    caption: 'The content landscape is shifting rapidly. Here\'s our complete content strategy framework for 2026 that\'s already delivering 3x engagement for our clients.',
    platform: 'Instagram',
    status: 'Editing',
    type: 'Carousel',
    scheduledDate: '2026-03-30',
    createdAt: '2026-03-17T16:00:00Z',
  },
  {
    id: '6',
    title: 'The Algorithm Decoded',
    caption: 'We analyzed 1,000+ posts across 3 platforms to crack the algorithm code. Here\'s what\'s actually working right now for organic reach in 2026.',
    platform: 'Instagram',
    status: 'Ready to Create',
    type: 'Reel',
    scheduledDate: '2026-04-02',
    createdAt: '2026-03-21T08:00:00Z',
  },
  {
    id: '7',
    title: 'Q1 Performance Review',
    caption: 'Q1 2026 is in the books and the numbers are in. Here\'s a full breakdown of our performance, what worked, what didn\'t, and our Q2 strategy.',
    platform: 'LinkedIn',
    status: 'Published',
    type: 'Talking Head',
    scheduledDate: '2026-03-05',
    createdAt: '2026-03-03T12:00:00Z',
  },
  {
    id: '8',
    title: 'Trending Audio Compilation',
    caption: 'These are the top trending audio tracks right now on Instagram Reels. Use these sounds to boost your reach and tap into existing viral momentum.',
    platform: 'Instagram',
    status: 'Scheduled',
    type: 'Reel',
    scheduledDate: '2026-03-27',
    createdAt: '2026-03-19T13:00:00Z',
  },
];

export const sampleCompetitors: Competitor[] = [
  {
    id: '1',
    name: 'ContentKing Co',
    category: 'Marketing Agency',
    youtube: 45000,
    instagram: 89000,
    linkedin: 12000,
    posts: 142,
    avgEngagement: 3.8,
    trend: 'up',
  },
  {
    id: '2',
    name: 'ViralVault Studio',
    category: 'Content Creation',
    youtube: 120000,
    instagram: 234000,
    linkedin: 8500,
    posts: 387,
    avgEngagement: 5.2,
    trend: 'up',
  },
  {
    id: '3',
    name: 'BrandFlow Agency',
    category: 'Digital Marketing',
    youtube: 28000,
    instagram: 67000,
    linkedin: 19000,
    posts: 98,
    avgEngagement: 2.9,
    trend: 'flat',
  },
];

export const sampleNews: NewsItem[] = [
  {
    id: '1',
    source: 'Reddit',
    subreddit: 'r/MachineLearning',
    upvotes: 2847,
    title: 'GPT-5 Multimodal Capabilities Leaked Benchmarks Show 40% Improvement',
    summary: 'Leaked internal benchmarks for GPT-5 suggest a 40% improvement in multimodal tasks compared to GPT-4o. The model reportedly handles video, audio, and text simultaneously with unprecedented accuracy, potentially reshaping content creation workflows.',
    timeAgo: '3h ago',
    url: 'https://reddit.com/r/MachineLearning',
  },
  {
    id: '2',
    source: 'RSS',
    title: 'Meta Launches AI-Powered Content Scheduling Tool for Creators',
    summary: 'Meta has announced a new AI-powered scheduling and content optimization tool integrated directly into Instagram and Facebook Creator Studio. The tool uses machine learning to predict optimal posting times and suggests caption improvements based on audience behavior.',
    timeAgo: '1h ago',
    url: 'https://techcrunch.com',
  },
  {
    id: '3',
    source: 'Reddit',
    subreddit: 'r/socialmedia',
    upvotes: 1203,
    title: 'Instagram Reels Algorithm Changes: What Creators Need to Know in 2026',
    summary: 'Instagram has quietly updated its Reels algorithm to prioritize "genuine interaction" signals over raw view counts. Saves, shares, and replays now carry significantly more weight. Creators report up to 60% changes in reach after the update rolled out last week.',
    timeAgo: '5h ago',
    url: 'https://reddit.com/r/socialmedia',
  },
  {
    id: '4',
    source: 'LocalLLaMA',
    subreddit: 'r/LocalLLaMA',
    upvotes: 892,
    title: 'Running Mistral 7B locally for content generation - full workflow',
    summary: 'A detailed guide on setting up Mistral 7B locally for end-to-end content generation pipelines. Covers caption writing, hashtag research, and A/B test variant generation. The author reports saving 8+ hours per week on content ideation.',
    timeAgo: '8h ago',
    url: 'https://reddit.com/r/LocalLLaMA',
  },
  {
    id: '5',
    source: 'RSS',
    title: "TikTok's New Creator Fund: Is It Worth It for Established Brands?",
    summary: "TikTok has overhauled its Creator Fund with higher payouts and new eligibility criteria. For established brands with over 100K followers, the new program offers CPM rates competitive with YouTube. We break down the numbers and whether it's worth pivoting strategy.",
    timeAgo: '2h ago',
    url: 'https://socialmediatoday.com',
  },
];

export const monthlyReachData: MonthlyMetric[] = [
  { month: 'Oct', instagram: 72000, twitter: 18000, linkedin: 31000 },
  { month: 'Nov', instagram: 85000, twitter: 22000, linkedin: 38000 },
  { month: 'Dec', instagram: 79000, twitter: 19000, linkedin: 42000 },
  { month: 'Jan', instagram: 94000, twitter: 25000, linkedin: 47000 },
  { month: 'Feb', instagram: 108000, twitter: 31000, linkedin: 55000 },
  { month: 'Mar', instagram: 113400, twitter: 38000, linkedin: 64300 },
];

export const engagementData: EngagementMetric[] = [
  { month: 'Oct', rate: 2.1 },
  { month: 'Nov', rate: 2.8 },
  { month: 'Dec', rate: 2.4 },
  { month: 'Jan', rate: 3.2 },
  { month: 'Feb', rate: 3.9 },
  { month: 'Mar', rate: 4.3 },
];
