export interface NicheProfile {
  id: string;
  label: string;
  emoji: string;
  tone: string;
  wordCount: string;
  pacing: string;
  wordsPerMinute: number;
  energyLevel: string;
  hookTemplates: string[];
  aesthetic: string;
  primaryColor: string;
  secondaryColor: string;
  preferredVisuals: string[];
  avoidVisuals: string;
  musicMood: string;
  captionStyle: string;
  sources: string[];
}

const NICHE_PROFILES: NicheProfile[] = [
  {
    id: 'tech',
    label: 'Tech & AI',
    emoji: '💻',
    tone: 'informed, slightly opinionated, conversational',
    wordCount: '150-170',
    pacing: 'punchy, short sentences',
    wordsPerMinute: 160,
    energyLevel: 'medium',
    hookTemplates: [
      'Contrarian take on trending topic',
      'Countdown urgency (3 things you missed)',
      'Bold prediction with evidence',
      'Breaking news reaction',
      'Myth-busting a popular belief',
      'Behind-the-scenes of a tech company',
      'Comparison: X vs Y and why it matters',
      'What nobody is talking about',
    ],
    aesthetic: 'dark backgrounds with neon/electric blue accents',
    primaryColor: '#00FF88',
    secondaryColor: '#4ECDC4',
    preferredVisuals: ['code on dark screens', 'server rooms', 'minimalist product shots', 'data visualizations'],
    avoidVisuals: 'stock photos of smiling office workers',
    musicMood: 'ambient electronic, minimal distraction',
    captionStyle: 'bold white text with neon highlight',
    sources: ['r/MachineLearning', 'Hacker News', 'TechCrunch RSS', 'Google Trends (technology)'],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    emoji: '🎮',
    tone: 'opinionated takes with genuine community knowledge',
    wordCount: '140-165',
    pacing: 'short, punchy sentences with fragments for emphasis',
    wordsPerMinute: 170,
    energyLevel: 'slightly breathless',
    hookTemplates: [
      'Corporate misstep nobody wanted',
      'Major announcement that shifts everything',
      'Community conflict or pro drama',
      'Market share shift between titles',
      'Datamined or insider leak',
      'Classic game revival or remaster',
      'Contrarian hot take backed by evidence',
    ],
    aesthetic: 'dark backgrounds with vibrant accents',
    primaryColor: '#FF4444',
    secondaryColor: '#FFD700',
    preferredVisuals: ['cinematic game screenshots', 'esports atmosphere', 'character poses'],
    avoidVisuals: 'generic stock imagery',
    musicMood: 'high energy electronic, gaming montage feel',
    captionStyle: 'bold text with red/gold accents',
    sources: ['gaming subreddits', 'Kotaku', 'Polygon', 'YouTube gaming trending'],
  },
  {
    id: 'finance',
    label: 'Finance',
    emoji: '📈',
    tone: 'clear, data driven, authoritative but accessible',
    wordCount: '140-160',
    pacing: 'measured, confident delivery',
    wordsPerMinute: 145,
    energyLevel: 'calm authority',
    hookTemplates: [
      'Shocking statistic that reframes the narrative',
      'Contrarian take on Wall Street consensus',
      'Central bank action and what it means',
      'Structural market shift nobody noticed',
      'Misunderstood financial event explained',
    ],
    aesthetic: 'dark backgrounds with green/red market accents',
    primaryColor: '#4ec9b0',
    secondaryColor: '#f44747',
    preferredVisuals: ['stock charts', 'trading floors', 'financial districts'],
    avoidVisuals: 'cartoon money or piggy banks',
    musicMood: 'ambient and corporate without lyrics',
    captionStyle: 'clean white text, professional look',
    sources: ['finance subreddits', 'Bloomberg RSS', 'Reuters', 'Yahoo Finance'],
  },
  {
    id: 'cooking',
    label: 'Cooking',
    emoji: '🍳',
    tone: 'warm, upbeat, enthusiastic foodie energy',
    wordCount: '130-150',
    pacing: 'friendly and inviting, medium pace',
    wordsPerMinute: 150,
    energyLevel: 'warm and upbeat',
    hookTemplates: [
      'Secret ingredient that changes everything',
      'Restaurant trick you can do at home',
      'Common cooking mistake everyone makes',
      'Under 60 seconds recipe hack',
      'Why your dish never tastes like the restaurant',
    ],
    aesthetic: 'warm lighting, close-up food shots',
    primaryColor: '#FF6B35',
    secondaryColor: '#F7C948',
    preferredVisuals: ['close-up food shots', 'kitchen prep', 'sizzling pans', 'plated dishes'],
    avoidVisuals: 'stock photos of people eating',
    musicMood: 'upbeat acoustic, warm and inviting',
    captionStyle: 'warm-toned text on food imagery',
    sources: ['r/Cooking', 'r/FoodPorn', 'Serious Eats RSS', 'Bon Appetit'],
  },
  {
    id: 'fitness',
    label: 'Fitness',
    emoji: '💪',
    tone: 'motivational, evidence-based, no-nonsense',
    wordCount: '140-160',
    pacing: 'energetic, direct commands',
    wordsPerMinute: 155,
    energyLevel: 'high',
    hookTemplates: [
      'Study proves this exercise is overrated',
      'One change that doubled my results',
      'The workout mistake killing your gains',
      'Why you are not seeing progress',
      'Science says stop doing this',
    ],
    aesthetic: 'gym lighting, high contrast',
    primaryColor: '#FF3366',
    secondaryColor: '#00D4FF',
    preferredVisuals: ['gym environments', 'exercise demonstrations', 'before/after data'],
    avoidVisuals: 'overly filtered or unrealistic body images',
    musicMood: 'high energy EDM, motivational beats',
    captionStyle: 'bold impact text, high contrast',
    sources: ['r/Fitness', 'r/bodybuilding', 'PubMed fitness studies'],
  },
  {
    id: 'science',
    label: 'Science',
    emoji: '🔬',
    tone: 'curious, wonder-driven, accessible',
    wordCount: '150-170',
    pacing: 'builds intrigue then delivers payoff',
    wordsPerMinute: 150,
    energyLevel: 'medium, rising with excitement',
    hookTemplates: [
      'Scientists just discovered something impossible',
      'This changes everything we thought we knew',
      'The experiment that broke physics',
      'Why this everyday thing is actually terrifying',
      'New study contradicts decades of research',
    ],
    aesthetic: 'space imagery, microscopic worlds, diagrams',
    primaryColor: '#7C4DFF',
    secondaryColor: '#00E5FF',
    preferredVisuals: ['space imagery', 'microscopic views', 'scientific diagrams', 'lab environments'],
    avoidVisuals: 'clip art or cartoon science',
    musicMood: 'atmospheric, wonder-inducing ambient',
    captionStyle: 'clean white on dark, scientific feel',
    sources: ['r/science', 'Nature RSS', 'New Scientist', 'ArXiv popular'],
  },
  {
    id: 'motivation',
    label: 'Motivation',
    emoji: '🔥',
    tone: 'intense, personal, raw honesty',
    wordCount: '130-150',
    pacing: 'dramatic pauses, building intensity',
    wordsPerMinute: 140,
    energyLevel: 'rising intensity',
    hookTemplates: [
      'The uncomfortable truth nobody tells you',
      'Why being comfortable is destroying you',
      'One mindset shift that changed everything',
      'Stop doing this if you want to succeed',
      'The real reason you are stuck',
    ],
    aesthetic: 'dark cinematic, moody lighting',
    primaryColor: '#FF8C00',
    secondaryColor: '#FFD700',
    preferredVisuals: ['cinematic landscapes', 'silhouettes', 'urban environments', 'abstract dark imagery'],
    avoidVisuals: 'cheesy inspirational stock photos',
    musicMood: 'dramatic orchestral, cinematic build',
    captionStyle: 'bold white impact text, dramatic',
    sources: ['r/getmotivated', 'r/Entrepreneur', 'motivational podcasts'],
  },
  {
    id: 'travel',
    label: 'Travel',
    emoji: '✈️',
    tone: 'adventurous, insider knowledge, storytelling',
    wordCount: '140-160',
    pacing: 'flowing, immersive narration',
    wordsPerMinute: 150,
    energyLevel: 'medium with excitement peaks',
    hookTemplates: [
      'This hidden gem has zero tourists',
      'Why you should never visit this famous spot',
      'Local secret the guidebooks won\'t tell you',
      'How to travel here for half the price',
      'The most underrated destination in the world',
    ],
    aesthetic: 'vibrant colors, golden hour lighting',
    primaryColor: '#00BCD4',
    secondaryColor: '#FF9800',
    preferredVisuals: ['landscape photography', 'local culture', 'aerial shots', 'food markets'],
    avoidVisuals: 'generic beach stock photos',
    musicMood: 'world music, acoustic, uplifting',
    captionStyle: 'warm text overlaid on travel footage',
    sources: ['r/travel', 'Lonely Planet RSS', 'Atlas Obscura'],
  },
  {
    id: 'true_crime',
    label: 'True Crime',
    emoji: '🔍',
    tone: 'suspenseful, measured, respectful of victims',
    wordCount: '160-180',
    pacing: 'slow build, deliberate pauses for tension',
    wordsPerMinute: 135,
    energyLevel: 'low, tense',
    hookTemplates: [
      'The case that still haunts investigators',
      'One detail that cracked the case wide open',
      'What the police missed for 20 years',
      'The most chilling 911 call ever recorded',
      'Nobody believed the witness until now',
    ],
    aesthetic: 'dark cinematography, noir lighting',
    primaryColor: '#B71C1C',
    secondaryColor: '#455A64',
    preferredVisuals: ['dark urban environments', 'evidence-style imagery', 'noir lighting'],
    avoidVisuals: 'graphic or exploitative imagery',
    musicMood: 'dark ambient, tense atmospheric',
    captionStyle: 'white text on dark, typewriter feel',
    sources: ['r/TrueCrime', 'r/UnresolvedMysteries', 'crime podcasts'],
  },
  {
    id: 'general',
    label: 'General',
    emoji: '📺',
    tone: 'engaging, informative, broad appeal',
    wordCount: '140-160',
    pacing: 'conversational, varied rhythm',
    wordsPerMinute: 155,
    energyLevel: 'medium',
    hookTemplates: [
      'You won\'t believe what just happened',
      'The story behind this viral moment',
      'Why everyone is talking about this',
      'Things that make absolutely no sense',
      'The truth behind the headline',
    ],
    aesthetic: 'clean, modern, well-lit',
    primaryColor: '#007acc',
    secondaryColor: '#4fc1ff',
    preferredVisuals: ['clean modern graphics', 'relevant b-roll', 'text overlays'],
    avoidVisuals: 'low quality or blurry images',
    musicMood: 'upbeat pop instrumental, mainstream feel',
    captionStyle: 'bold yellow text, high readability',
    sources: ['r/all trending', 'Google Trends', 'Twitter trending'],
  },
];

export default NICHE_PROFILES;
